#!/bin/sh

set -e
set -u

HOME_PACKAGES='
bash
fish
git
tmux
vim
'

CONFIG_PACKAGES='
nvim
'


if command -v stow >/dev/null ; then
    stow --verbose --target "$HOME" $HOME_PACKAGES
    for package in $CONFIG_PACKAGES ; do
        target=${XDG_CONFIG_HOME:-$HOME/.config/$package}
        stow --verbose --target "$target" $package
    done
else
    echo >&2 "Need to have stow installed."
    exit 1
fi
