#!/bin/sh

set -e
set -u

PACKAGES='
bash
fortune
git
tmux
vim
zsh
'


if command -v stow >/dev/null ; then
    stow $PACKAGES --target "$HOME"
else
    echo >&2 "Need to have stow installed."
    exit 1
fi
